# Generated by Django 5.1.2 on 2024-11-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_area", "0002_post_date_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="deleteFlag",
            field=models.BooleanField(default=False),
        ),
    ]
